# Generated by Django 4.2.2 on 2023-06-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
