# Generated by Django 4.2.2 on 2023-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(upload_to='passports/'),
        ),
    ]
